[[theme.fontFaces]]
family = "Roboto"
url = "https://cdn.jsdelivr.net/npm/@fontsource/roboto@5/files/roboto-latin-400-normal.woff2"
weight = 400
style = "normal"

[[theme.fontFaces]]
family = "Roboto"
url = "https://cdn.jsdelivr.net/npm/@fontsource/roboto@5/files/roboto-latin-500-normal.woff2"
weight = 500
style = "normal"

[[theme.fontFaces]]
family = "Roboto"
url = "https://cdn.jsdelivr.net/npm/@fontsource/roboto@5/files/roboto-latin-700-normal.woff2"
weight = 700
style = "normal"

[theme]
base = "light"
backgroundColor = "#EAFBF6"
secondaryBackgroundColor = "#7CF2D1"
textColor = "#000000"
primaryColor = "#1B4F72"
borderColor = "#9AD9C6"
linkColor = "#1B4F72"
font = "Roboto, sans-serif"

[theme.dark]
backgroundColor = "#121212"
secondaryBackgroundColor = "#1C1C1C"
textColor = "#FFFFFF"
primaryColor = "#4899CF"
borderColor = "#4A4A4A"
linkColor = "#7CC7EE"
font = "Roboto, sans-serif"

[server]
maxUploadSize = 20

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
